.\"------------------------------------------------------------
.\" Id - set Rv,revision, and Dt, Date using rcs-Id tag.
.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Id: xmg.1,v 1.1 1994/09/19 06:03:22 tes Exp $
.\"------------------------------------------------------------
.TH xmg 1 \*(Dt CITRI
.SH NAME
xmg \- An X interface to mgquery
.SH SYNOPSIS
.B xmg
[
.I collection-name
]
.SH DESCRIPTION
.B xmg
is an X interface to the
.BR mg (1)
information retrieval system.
.PP
Type a query in the ``Query'' box.  The escape key clears the query text.
.PP
The first line or so of each matching document is listed.
.PP
Click on any line to show the complete document.
.PP
Shift-click to show the document in a new window.
.PP
Press
.I Next
and
.I Previous
to cycle through the list of documents (shift works here too).
.PP
If you change the query, existing windows continue to refer to the
original query.
.PP
You can select either Boolean or ranked queries:
.RS
.TP "\w'\fIBoolean queries:\fP'u+2n"
.I "Boolean queries:"
use ``&'' for AND, ``|'' for OR, ``!'' for NOT, and parentheses for
grouping.
.TP
.I "Ranked queries:"
Documents are listed in order of relevance.  A weight is shown
alongside each.  Weights are normalized to 100 for the most relevant
document.  Choose
.I "Approximate Ranking"
for greater retrieval speed.
.RE
.PP
In document windows (other than the main window):
.RS
.br
Typing `n' = next document;
.br
Typing `N' = next document in new window;
.br
Typing `p' = previous document;
.br
Typing `P' = previous document in new window;
.br
Typing `q' = close window.
.RE
.SH ENVIRONMENT
.TP "\w'\fBMGDATA\fP'u+2n"
.SB MGDATA
If this environment variable exists, then its value is used as the
default directory where the
.BR mg (1)
collection files are.  If this variable does not exist, then the
directory \*(lq\fB.\fP\*(rq is used by default.  The command line
option
.BI \-d " directory"
overrides the directory in
.BR MGDATA .
.TP
.SB Xdefaults
To override the default font options, use RESOURCE_MANAGER properties
like the following in your
.I .Xdefaults
file:
.IP
.RS
.nf
.I "xmg.textfont: fixed"
.I "xmg.buttonfont: fixed"
.fi
.RE
.IP
To override the default query type of ranked, use
.IP
.RS
.I "xmg.querytype: boolean"
.RE
.IP
To override the default collection name (the first one listed by
.BR ls (1)
from your MGDATA environment variable), use
.IP
.RS
.I "xmg.collection: mail93"
.RE
.SH "SEE ALSO"
.na
.BR ls (1),
.BR mg (1),
.BR mg_compression_dict (1),
.BR mg_fast_comp_dict (1),
.BR mg_get (1),
.BR mg_invf_dict (1),
.BR mg_invf_dump (1),
.BR mg_invf_rebuild (1),
.BR mg_passes (1),
.BR mg_perf_hash_build (1),
.BR mg_text_estimate (1),
.BR mg_weights_build (1),
.BR mgbilevel (1),
.BR mgbuild (1),
.BR mgdictlist (1),
.BR mgfelics (1),
.BR mgquery (1),
.BR mgtic (1),
.BR mgticbuild (1),
.BR mgticdump (1),
.BR mgticprune (1),
.BR mgticstat (1).
