.\"------------------------------------------------------------
.\" Id - set Rv,revision, and Dt, Date using rcs-Id tag.
.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Id: mg_hilite_words.1,v 1.1 1995/06/06 01:59:45 tes Exp $
.\"------------------------------------------------------------
.TH mg_hilite_words 1 \*(Dt CITRI
.SH NAME
mg_hilite_words \- display text and highlight particular words which it contains
.SH SYNOPSIS
.B mg_hilite_words
.if n .ti +9n
[
.B --stem_method [0-3]
]
.if n .ti +9n
[
.B --style [bold|underline|italic|emphasis|strong]
]
.if n .ti +9n
[
.B --pager [less|more|html|???]
]
.if n .ti +9n
.I list-of-words-to-highlight

.SH DESCRIPTION
.B mg_hilite_words
reads text from stdin and outputs it into a pager such as
less. It's command arguments include a list of stemmed words
which if extracted from the text will be highlighted on the output
using a highlighting style.

It has been extended to output the highlighted text using html
straight to stdout.

.SH OPTIONS
Options may appear in any order, but the
.IR list-of-words-to-highlight ,
must be last.
.TP
.B --stem_method [0-3]
This option allows one to set the stemming method for the extraction of
the words from the incoming text.
This should match the way the inverted file index was created.
The default is 3, which is fold and stem.
.TP
.B --style [bold|underline|italic|emphasis|strong]
This option sets the highlighting style.
.IR Bold 
and 
.IR underline
are utilised by the pager or for html output.
.IR Italic,
.IR emphasis,
and
.IR strong
can only be used for html output.
.TP
.B --pager [less|more|html|???]
One can use the standard 
.IR less
or
.IR more
pages for displaying the highlighted text.
Or one can generate highlighted html using the paging setting of
.IR html.
One can also specify a custom pager of their own choosing (i.e. ???).
.TP
.B list-of-words-to-highlight
Each word is taken as a command line argument.
Each word should already be stemmed and folded according to
the stem option.
.SH USAGE
This program was written primarily to be called by 
.IR mgquery(1)
.
When the user selects the mode of "hilite" then this program
is called for displaying the query-result documents instead of
just the pager.
.SH "SEE ALSO"
.na
.BR mgquery (1).


