.\"------------------------------------------------------------
.\" Id - set Rv,revision, and Dt, Date using rcs-Id tag.
.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Id: mgdictlist.1,v 1.1 1994/09/19 06:03:11 tes Exp $
.\"------------------------------------------------------------
.TH mgdictlist 1 \*(Dt CITRI
.SH NAME
mgdictlist \- list the contents of a dictionary
.SH SYNOPSIS
.B mgdictlist
[
.B \-q
]
.I filename
.SH DESCRIPTION
.B mgdictlist
lists the contents of either a compressed compression dictionary, a
text statistics file, or a compressed stemmed dictionary.  Unlike all
the other programs in the
.BR mg (1)
suite, it is necessary to specify the complete pathname of the
dictionary to list.
.SH OPTIONS
The
.I filename
must be last.
.TP "\w'\fIfilename\fP'u+2n"
.B \-q
Generate an abbreviated output (machine-readable rather than
human-readable).
.TP
.I filename
This is the name of the dictionary to list.
.B mgdictlist
automatically detects whether the file is a compressed compression
dictionary, text statistics file, or a compressed stemmed dictionary.
.SH FILES
.TP 20
.B *.text.dict
Text statistics file.
.TP
.B *.text.dict
Compressed compression dictionary.
.TP
.B *.invf.build
Compressed stemmed dictionary.
.SH "SEE ALSO"
.na
.BR mg (1),
.BR mg_compression_dict (1),
.BR mg_fast_comp_dict (1),
.BR mg_get (1),
.BR mg_invf_dict (1),
.BR mg_invf_dump (1),
.BR mg_invf_rebuild (1),
.BR mg_passes (1),
.BR mg_perf_hash_build (1),
.BR mg_text_estimate (1),
.BR mg_weights_build (1),
.BR mgbilevel (1),
.BR mgbuild (1),
.BR mgfelics (1),
.BR mgquery (1),
.BR mgstat (1),
.BR mgtic (1),
.BR mgticbuild (1),
.BR mgticdump (1),
.BR mgticprune (1),
.BR mgticstat (1).
