DISTFILES = \
  detolnay.ptm           monaLisa.pgm \
  Makefile               detolnay.txt           monaLisa.txt \
  canal_excavation.pbm   helicopter.pbm         venturi.txt  \
  clark.txt              helicopter.txt

dist:
	ln $(DISTFILES) $(distdir)
